/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BankApp;

import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JLabel;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Bank_app extends javax.swing.JFrame {

    private static final String CUSTOMER_FILE_PATH = Path.getCustomer();
    private static final String PAYMENTS_FILE_PATH = Path.getPayment();
    private static final String USER_FILE_PATH = Path.getUser();

    private double a, Housingloan, Personalloan, vechileloan, result;
    private int months;
    Customer c;

    public Bank_app(Customer t) {
        this.c = t;
        initComponents();
        Name.setText(c.firstName + " " + c.secondName);
        NetBalance.setText("Net balance: " + c.getMoney());
        String[] names = new String[4];
        for (int i = 0; i < 4; i++) {
            names[i] = dashtable.getColumnName(i);
        }
        dashtable.setModel(new DefaultTableModel(null, names));

        try {
            File f = new File(PAYMENTS_FILE_PATH);
            Scanner s = new Scanner(f);
            for (int i = 0; i < 3; i++) {
                String idd = s.next() + " " + s.next() + " " + s.next() + " " + s.next();

                if (idd.equals(c.getId())) {
                    String[] arr = new String[4];
                    arr[0] = s.next();
                    arr[1] = s.next();
                    arr[2] = s.next();
                    arr[3] = s.next();
                    DefaultTableModel tb = (DefaultTableModel) dashtable.getModel();
                    tb.addRow(arr);
                } else {
                    s.nextLine();
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Bank_app.class.getName()).log(Level.SEVERE, null, ex);
        }
        a = 0;
        months = 0;
        result = 0;
        Housingloan = 0;
        Personalloan = 0;
        vechileloan = 0;
        setResizable(false);
    }

    public Bank_app() {

        initComponents();

        a = 0;
        months = 0;
        result = 0;

        Housingloan = 0;
        Personalloan = 0;
        vechileloan = 0;
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        dash = new javax.swing.JButton();
        trans = new javax.swing.JButton();
        transfer = new javax.swing.JButton();
        loan = new javax.swing.JButton();
        services = new javax.swing.JButton();
        settings = new javax.swing.JButton();
        taps = new javax.swing.JTabbedPane();
        dash_Panel = new javax.swing.JPanel();
        NetBalance = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dashtable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        trans_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transtable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        transfer_Panel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        transferb = new javax.swing.JButton();
        loan_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tybecb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf = new javax.swing.JTextField();
        amountcb = new javax.swing.JComboBox<>();
        total = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        services_Panel = new javax.swing.JPanel();
        combo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        billnum = new javax.swing.JTextPane();
        pay = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        settings_Panel = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        old_pass = new javax.swing.JTextField();
        new_pass = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        new_pass2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab2", jPanel17);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab3", jPanel18);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel16);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 680));

        dash.setBackground(new java.awt.Color(0, 102, 102));
        dash.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dash.setText("Dash Board");
        dash.setPreferredSize(new java.awt.Dimension(90, 85));
        dash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashActionPerformed(evt);
            }
        });

        trans.setBackground(new java.awt.Color(0, 102, 102));
        trans.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        trans.setText("Transaction");
        trans.setPreferredSize(new java.awt.Dimension(90, 85));
        trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transActionPerformed(evt);
            }
        });

        transfer.setBackground(new java.awt.Color(0, 102, 102));
        transfer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        transfer.setText("Transfer");
        transfer.setPreferredSize(new java.awt.Dimension(90, 85));
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });

        loan.setBackground(new java.awt.Color(0, 102, 102));
        loan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loan.setText("Loan");
        loan.setPreferredSize(new java.awt.Dimension(90, 85));
        loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanActionPerformed(evt);
            }
        });

        services.setBackground(new java.awt.Color(0, 102, 102));
        services.setText("Local Services");
        services.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        services.setPreferredSize(new java.awt.Dimension(90, 85));
        services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesActionPerformed(evt);
            }
        });

        settings.setBackground(new java.awt.Color(0, 102, 102));
        settings.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        settings.setText("Settings");
        settings.setPreferredSize(new java.awt.Dimension(90, 85));
        settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dash, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(services, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trans, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(dash, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(trans, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(loan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(services, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 130, 760));

        dash_Panel.setBackground(new java.awt.Color(153, 153, 153));

        NetBalance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NetBalance.setText("2");

        Name.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Name.setText("1");

        dashtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Refrence Number", "Description", "Balance"
            }
        ));
        jScrollPane3.setViewportView(dashtable);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setText("Name:");

        javax.swing.GroupLayout dash_PanelLayout = new javax.swing.GroupLayout(dash_Panel);
        dash_Panel.setLayout(dash_PanelLayout);
        dash_PanelLayout.setHorizontalGroup(
            dash_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash_PanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel15)
                .addGap(70, 70, 70)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(NetBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addComponent(jScrollPane3)
        );
        dash_PanelLayout.setVerticalGroup(
            dash_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash_PanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(dash_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NetBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        taps.addTab("tab1", dash_Panel);

        trans_Panel.setBackground(new java.awt.Color(153, 153, 153));

        transtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Refrence number", "Description", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(transtable);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel10.setBackground(new java.awt.Color(0, 153, 153));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Transactions");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout trans_PanelLayout = new javax.swing.GroupLayout(trans_Panel);
        trans_Panel.setLayout(trans_PanelLayout);
        trans_PanelLayout.setHorizontalGroup(
            trans_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(trans_PanelLayout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trans_PanelLayout.setVerticalGroup(
            trans_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trans_PanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        taps.addTab("tab2", trans_Panel);

        transfer_Panel.setBackground(new java.awt.Color(153, 153, 153));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton3.setText("Bank Transfer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Recipient Accont:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Ammount of transfer:");

        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Sender Accont:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        transferb.setBackground(new java.awt.Color(0, 102, 102));
        transferb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        transferb.setText("Transfer");
        transferb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transfer_PanelLayout = new javax.swing.GroupLayout(transfer_Panel);
        transfer_Panel.setLayout(transfer_PanelLayout);
        transfer_PanelLayout.setHorizontalGroup(
            transfer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transfer_PanelLayout.createSequentialGroup()
                .addGroup(transfer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transfer_PanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(transfer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, transfer_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, transfer_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(transfer_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGroup(transfer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(transfer_PanelLayout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(jButton3))
                                    .addGroup(transfer_PanelLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(transfer_PanelLayout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transfer_PanelLayout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(transferb, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transfer_PanelLayout.setVerticalGroup(
            transfer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transfer_PanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton3)
                .addGap(79, 79, 79)
                .addGroup(transfer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(transfer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(transfer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(transferb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        taps.addTab("tab3", transfer_Panel);

        loan_Panel.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Welcome to Loan Window");

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Select tybe of loan :");

        tybecb.setForeground(new java.awt.Color(255, 204, 204));
        tybecb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Housing", "Personal", "Vechile" }));
        tybecb.setToolTipText("");
        tybecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tybecbActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Amount :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Total:");

        amountcb.setForeground(new java.awt.Color(255, 204, 204));
        amountcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1000", "3000", "5000", "10000", "20000", "50000", "100000", "300000", "500000", "1000000" }));
        amountcb.setToolTipText("");
        amountcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountcbActionPerformed(evt);
            }
        });

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Duration :");

        javax.swing.GroupLayout loan_PanelLayout = new javax.swing.GroupLayout(loan_Panel);
        loan_Panel.setLayout(loan_PanelLayout);
        loan_PanelLayout.setHorizontalGroup(
            loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loan_PanelLayout.createSequentialGroup()
                .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loan_PanelLayout.createSequentialGroup()
                        .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loan_PanelLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tybecb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf)
                                    .addComponent(amountcb, 0, 160, Short.MAX_VALUE)))
                            .addGroup(loan_PanelLayout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(95, 95, 95)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loan_PanelLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loan_PanelLayout.setVerticalGroup(
            loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loan_PanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tybecb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountcb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        taps.addTab("tab4", loan_Panel);

        services_Panel.setBackground(new java.awt.Color(153, 153, 153));

        combo.setBackground(new java.awt.Color(0, 102, 102));
        combo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Water", "Electricity", "Gas", "Internet" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(billnum);

        pay.setBackground(new java.awt.Color(0, 102, 102));
        pay.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        pay.setText("Pay");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Enter Bill  number:");

        jTextField2.setBackground(new java.awt.Color(0, 102, 102));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTextField2.setText("Local Services");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout services_PanelLayout = new javax.swing.GroupLayout(services_Panel);
        services_Panel.setLayout(services_PanelLayout);
        services_PanelLayout.setHorizontalGroup(
            services_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(services_PanelLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(32, 32, 32)
                .addGroup(services_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(services_PanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(services_PanelLayout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        services_PanelLayout.setVerticalGroup(
            services_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(services_PanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196)
                .addGroup(services_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(services_PanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(services_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pay)
                .addGap(211, 211, 211))
        );

        taps.addTab("tab7", services_Panel);

        settings_Panel.setBackground(new java.awt.Color(153, 153, 153));

        jButton5.setBackground(new java.awt.Color(0, 0, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setText("Logout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setText("Help!");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Click here to Choose mode");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dark Mode", "Light Mode" }));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText(" change Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        old_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                old_passActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("enter new password");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("enter old password");

        new_pass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_pass2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("renter new password");

        javax.swing.GroupLayout settings_PanelLayout = new javax.swing.GroupLayout(settings_Panel);
        settings_Panel.setLayout(settings_PanelLayout);
        settings_PanelLayout.setHorizontalGroup(
            settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settings_PanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(settings_PanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settings_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settings_PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(old_pass)
                    .addComponent(new_pass)
                    .addComponent(new_pass2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(settings_PanelLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(717, Short.MAX_VALUE)))
        );
        settings_PanelLayout.setVerticalGroup(
            settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settings_PanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settings_PanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(settings_PanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(old_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(new_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(new_pass2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton7)
                .addGap(68, 68, 68))
            .addGroup(settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(settings_PanelLayout.createSequentialGroup()
                    .addGap(177, 177, 177)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(531, Short.MAX_VALUE)))
        );

        taps.addTab("tab8", settings_Panel);

        getContentPane().add(taps, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -40, 980, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transActionPerformed
        String[] names = new String[4];
        for (int i = 0; i < 4; i++) {
            names[i] = transtable.getColumnName(i);
        }
        transtable.setModel(new DefaultTableModel(null, names));
        taps.setSelectedIndex(1);

        try {
            File f = new File(PAYMENTS_FILE_PATH);
            Scanner s = new Scanner(f);
            while (s.hasNext()) {
                String idd = s.next() + " " + s.next() + " " + s.next() + " " + s.next();

                if (idd.equals(c.getId())) {
                    String[] arr = new String[4];
                    arr[0] = s.next();
                    arr[1] = s.next();
                    arr[2] = s.next();
                    arr[3] = s.next();
                    DefaultTableModel tb = (DefaultTableModel) transtable.getModel();
                    tb.addRow(arr);
                } else {
                    s.nextLine();
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Bank_app.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_transActionPerformed

    private void loanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanActionPerformed
        taps.setSelectedIndex(3);
    }//GEN-LAST:event_loanActionPerformed

    private void servicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesActionPerformed
        taps.setSelectedIndex(4);
    }//GEN-LAST:event_servicesActionPerformed

    private void dashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashActionPerformed
        taps.setSelectedIndex(0);
        NetBalance.setText("Net balance: " + c.getMoney());
        String[] names = new String[4];
        for (int i = 0; i < 4; i++) {
            names[i] = dashtable.getColumnName(i);
        }
        dashtable.setModel(new DefaultTableModel(null, names));

        try {
            File f = new File(PAYMENTS_FILE_PATH);
            Scanner s = new Scanner(f);
            for (int i = 0; i < 3; i++) {
                String idd = s.next() + " " + s.next() + " " + s.next() + " " + s.next();

                if (idd.equals(c.getId())) {
                    String[] arr = new String[4];
                    arr[0] = s.next();
                    arr[1] = s.next();
                    arr[2] = s.next();
                    arr[3] = s.next();
                    DefaultTableModel tb = (DefaultTableModel) dashtable.getModel();
                    tb.addRow(arr);
                } else {
                    s.nextLine();
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Bank_app.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dashActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
        taps.setSelectedIndex(2);
    }//GEN-LAST:event_transferActionPerformed

    private void settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed
        taps.setSelectedIndex(5);
    }//GEN-LAST:event_settingsActionPerformed

    private void new_pass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_pass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_pass2ActionPerformed

    private void old_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_old_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_old_passActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            List<User> l = DataFile.readUserFromFile(USER_FILE_PATH);

            for (int i = 0; i < l.size(); i++) {
                User existingUser = l.get(i);
                if ((existingUser.getId().equals(c.getId()))) {
                    if (old_pass.getText().equals(existingUser.getPass())) {
                        if (new_pass.getText().equals(new_pass2.getText())) {
                            existingUser.setPass(new_pass.getText());
                            l.set(i, existingUser);
                            break;

                        } else {
                            JOptionPane.showMessageDialog(null, "Password dismatch stubid");
                            break;
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Wrong Password stubid");
                    }

                    break;

                }

            }
            DataFile.writeUsersToFile(USER_FILE_PATH, l);

        } catch (IOException ex) {
            Logger.getLogger(Bank_app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Bank_app.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JOptionPane.showMessageDialog(null, "call 911\nto get help");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        File f = new File("temp.txt");
        if (f.exists()) {
            f.delete();
        }
        dispose();
        try {
            Thread.sleep(500);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        try {
            new Bank_Login().show();
        } catch (IOException ex) {
            Logger.getLogger(Bank_app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Bank_app.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        String x;
        x = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
        if (x.equals("Dark Mode")) {
            settings_Panel.setBackground(Color.DARK_GRAY);
            services_Panel.setBackground(Color.DARK_GRAY);
            loan_Panel.setBackground(Color.DARK_GRAY);
            transfer_Panel.setBackground(Color.DARK_GRAY);
            trans_Panel.setBackground(Color.DARK_GRAY);
            dash_Panel.setBackground(Color.DARK_GRAY);
            settings.setBackground(Color.BLACK);
            services.setBackground(Color.BLACK);
            transfer.setBackground(Color.BLACK);
            trans.setBackground(Color.BLACK);
            dash.setBackground(Color.BLACK);
            loan.setBackground(Color.BLACK);
            jPanel1.setBackground(new Color(0, 0, 0));
            loan.setForeground(Color.WHITE);
            settings.setForeground(Color.WHITE);
            services.setForeground(Color.WHITE);
            trans.setForeground(Color.WHITE);
            dash.setForeground(Color.WHITE);
            transfer.setForeground(Color.WHITE);

        }
        if (x.equals("Light Mode")) {
            settings_Panel.setBackground(Color.LIGHT_GRAY);
            services_Panel.setBackground(Color.LIGHT_GRAY);
            loan_Panel.setBackground(Color.LIGHT_GRAY);
            transfer_Panel.setBackground(Color.LIGHT_GRAY);
            trans_Panel.setBackground(Color.LIGHT_GRAY);
            dash_Panel.setBackground(Color.LIGHT_GRAY);
            settings.setBackground(Color.green);
            services.setBackground(Color.green);
            transfer.setBackground(Color.green);
            trans.setBackground(Color.green);
            dash.setBackground(Color.green);
            loan.setBackground(Color.green);
            loan.setForeground(Color.WHITE);
            jPanel1.setBackground(Color.WHITE);
            settings.setForeground(Color.WHITE);
            services.setForeground(Color.WHITE);
            trans.setForeground(Color.WHITE);
            dash.setForeground(Color.WHITE);
            transfer.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        String water, elec, gas, net;
        water = "src\\main\\java\\BankApp\\Bills\\Water.txt";
        elec = "src\\main\\java\\BankApp\\Bills\\Elec.txt";
        gas = "src\\main\\java\\BankApp\\Bills\\Gas.txt";
        net = "src\\main\\java\\BankApp\\Bills\\Net.txt";
        String file = "";
        if (combo.getSelectedIndex() == 0) {
            file = water;
        } else if (combo.getSelectedIndex() == 1) {
            file = elec;
        } else if (combo.getSelectedIndex() == 2) {
            file = gas;
        } else if (combo.getSelectedIndex() == 3) {
            file = net;
        }

        File b = new File(file);
        double current = Double.parseDouble(c.getMoney());
        Scanner s;
        boolean isexist = false;
        try {
            s = new Scanner(b);
            while (s.hasNext()) {
                if (billnum.getText().trim().equals("")) {
                    JOptionPane.showMessageDialog(this, "Enter The amount of bill");
                    isexist = true;
                    break;
                } else if (billnum.getText().equals((String) s.next())) {
                    isexist = true;
                    Double amountt;
                    amountt = Double.valueOf((String) s.next());
                    if (amountt <= current) {
                        current -= amountt;
                        c.setMoney(Double.toString(current));
                        //hoda y7tha fe el file bta3 customer
                        try {
                            List<Customer> l = DataFile.readCustomersFromFile(CUSTOMER_FILE_PATH);
                            for (int i = 0; i < l.size(); i++) {
                                Customer existingCustomer = l.get(i);
                                if ((existingCustomer.getFirstName() + existingCustomer.getSecondName()).equals(c.getFirstName() + c.getSecondName())) {
                                    l.set(i, c);
                                    break;
                                }
                            }
                            DataFile.writeCustomersToFile(CUSTOMER_FILE_PATH, l);
                            DataFile.writeCustomerToFile("temp.txt", c);

                        } catch (FileNotFoundException e) {
                            JOptionPane.showMessageDialog(this, "File Not Found !", "ERROR 102", JOptionPane.ERROR_MESSAGE);
                        } catch (IOException e) {
                            JOptionPane.showMessageDialog(this, "Input or Output File Erorr !", "ERROR 103", JOptionPane.ERROR_MESSAGE);
                        } catch (ClassNotFoundException e) {
                            JOptionPane.showMessageDialog(this, "Cannot Found Class File !", "ERROR 104", JOptionPane.ERROR_MESSAGE);
                        }
                        JOptionPane.showMessageDialog(this, "Sucussufully Bill");
                        billnum.setText("");
                        break;
                    } else {
                        JOptionPane.showMessageDialog(this, "Not Enough Money");
                        break;
                    }
                }
            }
            if (!isexist) {
                JOptionPane.showMessageDialog(this, "Wrong bill number");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Bank_app.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_payActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void amountcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountcbActionPerformed

    }//GEN-LAST:event_amountcbActionPerformed

    private void tybecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tybecbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tybecbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        a = Integer.parseInt(amountcb.getItemAt(amountcb.getSelectedIndex()));
        months = Integer.parseInt(tf.getText());
        if (!(0 < months)) {
            JOptionPane.showMessageDialog(this, "you can't Enter negative Month");

        }

        String tybe = tybecb.getItemAt(tybecb.getSelectedIndex());

        Housingloan = 0.15;
        Personalloan = 0.15;
        vechileloan = 0.1;

        switch (tybe) {
            case "Housing" -> {

                result = (a * months * Housingloan) + a;

            }
            case "Personal" -> {
                result = (a * months * Personalloan) + a;
            }
            case "Vechile" -> {
                result = (a * months * vechileloan) + a;
            }
            default -> {
            }
        }

        if (a > Double.parseDouble(c.getMoney())) {

            JOptionPane.showMessageDialog(this, "Your Balance isn't Enough");

        } else {

            total.setText(Double.toString(result));

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void transferbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferbActionPerformed
        double transferammount = Double.parseDouble(amount.getText());
        double currentmony = Double.parseDouble(c.getMoney());
        if (transferammount > currentmony) {
            JOptionPane.showMessageDialog(null, "not enough amount\n plesse try again when yous have enough money you poor");
        } else {
            currentmony -= transferammount;
            c.setMoney(Double.toString(currentmony));
            try {
                List<Customer> l = DataFile.readCustomersFromFile(CUSTOMER_FILE_PATH);
                for (int i = 0; i < l.size(); i++) {
                    Customer existingCustomer = l.get(i);
                    if ((existingCustomer.getFirstName() + existingCustomer.getSecondName()).equals(c.getFirstName() + c.getSecondName())) {
                        l.set(i, c);
                        break;
                    }
                }
                DataFile.writeCustomersToFile(CUSTOMER_FILE_PATH, l);
                DataFile.writeCustomerToFile("temp.txt", c);
                JOptionPane.showMessageDialog(null, "Transfer Done Sucussufully");

            } catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(this, "File Not Found !", "ERROR 102", JOptionPane.ERROR_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Input or Output File Erorr !", "ERROR 103", JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(this, "Cannot Found Class File !", "ERROR 104", JOptionPane.ERROR_MESSAGE);
            }

            ZonedDateTime now = ZonedDateTime.now();
            DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

            String formattedDateTime = now.format(dateTimeFormatter);
            Random r = new Random();
            int min = 10000000;
            int max = 99999999;
            int randomEightDigitNumber = r.nextInt((max - min) + 1) + min;
            Payments p = new Payments(formattedDateTime, Integer.toString(randomEightDigitNumber), "Transaction", c.getId(), Double.parseDouble(amount.getText()));
            try {
                FileWriter f = new FileWriter(PAYMENTS_FILE_PATH, true);
                PrintWriter pp = new PrintWriter(f);
                pp.println(c.getId() + " " + formattedDateTime + " " + randomEightDigitNumber + " " + "Transfer" + " " + transferammount);
                pp.close();
            } catch (IOException ex) {
                Logger.getLogger(Bank_app.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_transferbActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bank_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Bank_app().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel NetBalance;
    private javax.swing.JTextField amount;
    private javax.swing.JComboBox<String> amountcb;
    private javax.swing.JTextPane billnum;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton dash;
    private javax.swing.JPanel dash_Panel;
    private javax.swing.JTable dashtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton loan;
    private javax.swing.JPanel loan_Panel;
    private javax.swing.JTextField new_pass;
    private javax.swing.JTextField new_pass2;
    private javax.swing.JTextField old_pass;
    private javax.swing.JButton pay;
    private javax.swing.JButton services;
    private javax.swing.JPanel services_Panel;
    private javax.swing.JButton settings;
    private javax.swing.JPanel settings_Panel;
    private javax.swing.JTabbedPane taps;
    private javax.swing.JTextField tf;
    private javax.swing.JTextField total;
    private javax.swing.JButton trans;
    private javax.swing.JPanel trans_Panel;
    private javax.swing.JButton transfer;
    private javax.swing.JPanel transfer_Panel;
    private javax.swing.JButton transferb;
    private javax.swing.JTable transtable;
    private javax.swing.JComboBox<String> tybecb;
    // End of variables declaration//GEN-END:variables
}
