/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BankApp;

import java.util.*;
import java.util.logging.Level;

import javax.swing.JOptionPane;
 
public class Bank_app extends javax.swing.JFrame {
    String id;
    private int a,Housingloan,Personalloan,vechileloan;
    private int months;
 
    private float result;
    public Bank_app(String id) {
        this.id = id;
        initComponents();
        
  
        
    }
    public Bank_app() {
        this.id = null;
        initComponents();
                 total.setVisible(false);
            a=0;
            months=0;
         result=0;
    
         Housingloan=0;
       Personalloan=0;
         vechileloan=0;
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        dash = new javax.swing.JButton();
        trans = new javax.swing.JButton();
        transfer = new javax.swing.JButton();
        loan = new javax.swing.JButton();
        wallets = new javax.swing.JButton();
        messages = new javax.swing.JButton();
        services = new javax.swing.JButton();
        settings = new javax.swing.JButton();
        taps = new javax.swing.JTabbedPane();
        dash_Panel = new javax.swing.JPanel();
        trans_Panel = new javax.swing.JPanel();
        transfer_Panel = new javax.swing.JPanel();
        loan_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tybecb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf = new javax.swing.JTextField();
        amountcb = new javax.swing.JComboBox<>();
        total = new javax.swing.JTextField();
        wallets_Panel = new javax.swing.JPanel();
        messages_Panel = new javax.swing.JPanel();
        services_Panel = new javax.swing.JPanel();
        settings_Panel = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab2", jPanel17);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab3", jPanel18);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel16);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 680));

        dash.setBackground(new java.awt.Color(0, 102, 102));
        dash.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dash.setText("Dash Board");
        dash.setPreferredSize(new java.awt.Dimension(90, 85));
        dash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashActionPerformed(evt);
            }
        });

        trans.setBackground(new java.awt.Color(0, 102, 102));
        trans.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        trans.setText("Transaction");
        trans.setPreferredSize(new java.awt.Dimension(90, 85));
        trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transActionPerformed(evt);
            }
        });

        transfer.setBackground(new java.awt.Color(0, 102, 102));
        transfer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        transfer.setText("Transfer");
        transfer.setPreferredSize(new java.awt.Dimension(90, 85));
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });

        loan.setBackground(new java.awt.Color(0, 102, 102));
        loan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loan.setText("Loan");
        loan.setPreferredSize(new java.awt.Dimension(90, 85));
        loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanActionPerformed(evt);
            }
        });

        wallets.setBackground(new java.awt.Color(0, 102, 102));
        wallets.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        wallets.setText("My Wallets");
        wallets.setPreferredSize(new java.awt.Dimension(90, 85));
        wallets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walletsActionPerformed(evt);
            }
        });

        messages.setBackground(new java.awt.Color(0, 102, 102));
        messages.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        messages.setText("Messages");
        messages.setPreferredSize(new java.awt.Dimension(90, 85));
        messages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messagesActionPerformed(evt);
            }
        });

        services.setBackground(new java.awt.Color(0, 102, 102));
        services.setText("Local Services");
        services.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        services.setPreferredSize(new java.awt.Dimension(90, 85));
        services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesActionPerformed(evt);
            }
        });

        settings.setBackground(new java.awt.Color(0, 102, 102));
        settings.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        settings.setText("Settings");
        settings.setPreferredSize(new java.awt.Dimension(90, 85));
        settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dash, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messages, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(services, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wallets, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trans, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dash, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trans, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wallets, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messages, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(services, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 130, 690));

        dash_Panel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout dash_PanelLayout = new javax.swing.GroupLayout(dash_Panel);
        dash_Panel.setLayout(dash_PanelLayout);
        dash_PanelLayout.setHorizontalGroup(
            dash_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        dash_PanelLayout.setVerticalGroup(
            dash_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        taps.addTab("tab1", dash_Panel);

        trans_Panel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout trans_PanelLayout = new javax.swing.GroupLayout(trans_Panel);
        trans_Panel.setLayout(trans_PanelLayout);
        trans_PanelLayout.setHorizontalGroup(
            trans_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        trans_PanelLayout.setVerticalGroup(
            trans_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        taps.addTab("tab2", trans_Panel);

        transfer_Panel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout transfer_PanelLayout = new javax.swing.GroupLayout(transfer_Panel);
        transfer_Panel.setLayout(transfer_PanelLayout);
        transfer_PanelLayout.setHorizontalGroup(
            transfer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        transfer_PanelLayout.setVerticalGroup(
            transfer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        taps.addTab("tab3", transfer_Panel);

        loan_Panel.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Welcome to Loan Window");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Select tybe of loan :");

        tybecb.setForeground(new java.awt.Color(255, 204, 204));
        tybecb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Housing", "Personal", "Vechile" }));
        tybecb.setToolTipText("");
        tybecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tybecbActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Amount :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Duration :");

        amountcb.setForeground(new java.awt.Color(255, 204, 204));
        amountcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1000", "3000", "5000", "10000", "20000", "50000", "100000", "300000", "500000", "1000000" }));
        amountcb.setToolTipText("");
        amountcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountcbActionPerformed(evt);
            }
        });

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loan_PanelLayout = new javax.swing.GroupLayout(loan_Panel);
        loan_Panel.setLayout(loan_PanelLayout);
        loan_PanelLayout.setHorizontalGroup(
            loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loan_PanelLayout.createSequentialGroup()
                .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loan_PanelLayout.createSequentialGroup()
                        .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loan_PanelLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tybecb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf)
                                    .addComponent(amountcb, 0, 160, Short.MAX_VALUE)))
                            .addGroup(loan_PanelLayout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(82, 82, 82)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loan_PanelLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        loan_PanelLayout.setVerticalGroup(
            loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loan_PanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tybecb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountcb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(loan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        taps.addTab("tab4", loan_Panel);

        wallets_Panel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout wallets_PanelLayout = new javax.swing.GroupLayout(wallets_Panel);
        wallets_Panel.setLayout(wallets_PanelLayout);
        wallets_PanelLayout.setHorizontalGroup(
            wallets_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        wallets_PanelLayout.setVerticalGroup(
            wallets_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        taps.addTab("tab5", wallets_Panel);

        messages_Panel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout messages_PanelLayout = new javax.swing.GroupLayout(messages_Panel);
        messages_Panel.setLayout(messages_PanelLayout);
        messages_PanelLayout.setHorizontalGroup(
            messages_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        messages_PanelLayout.setVerticalGroup(
            messages_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        taps.addTab("tab6", messages_Panel);

        services_Panel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout services_PanelLayout = new javax.swing.GroupLayout(services_Panel);
        services_Panel.setLayout(services_PanelLayout);
        services_PanelLayout.setHorizontalGroup(
            services_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        services_PanelLayout.setVerticalGroup(
            services_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        taps.addTab("tab7", services_Panel);

        settings_Panel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout settings_PanelLayout = new javax.swing.GroupLayout(settings_Panel);
        settings_Panel.setLayout(settings_PanelLayout);
        settings_PanelLayout.setHorizontalGroup(
            settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        settings_PanelLayout.setVerticalGroup(
            settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        taps.addTab("tab8", settings_Panel);

        getContentPane().add(taps, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1010, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transActionPerformed
        taps.setSelectedIndex(1);
    }//GEN-LAST:event_transActionPerformed

    private void loanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanActionPerformed
        taps.setSelectedIndex(3);
    }//GEN-LAST:event_loanActionPerformed

    private void messagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messagesActionPerformed
        taps.setSelectedIndex(5);
    }//GEN-LAST:event_messagesActionPerformed

    private void servicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesActionPerformed
        taps.setSelectedIndex(6);
    }//GEN-LAST:event_servicesActionPerformed

    private void dashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashActionPerformed
        taps.setSelectedIndex(0);
    }//GEN-LAST:event_dashActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
        taps.setSelectedIndex(2);
    }//GEN-LAST:event_transferActionPerformed

    private void walletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walletsActionPerformed
        taps.setSelectedIndex(4);
    }//GEN-LAST:event_walletsActionPerformed

    private void settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed
        taps.setSelectedIndex(7);
    }//GEN-LAST:event_settingsActionPerformed

    private void tybecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tybecbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tybecbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
         
          a=Integer.parseInt(amountcb.getItemAt(amountcb.getSelectedIndex()));
        months=Integer.parseInt(tf.getText());
        if(!(0<months))
        {
             JOptionPane.showMessageDialog(this, "you can't Enter negative Month");
         
        }
      
        String tybe =tybecb.getItemAt(tybecb.getSelectedIndex());
        float amountpermonth=a/months;
    Housingloan=5;
    Personalloan=5;
    vechileloan=4;
    
        switch (tybe) {
            case "Housing" -> {
                result=(Housingloan*a)/(100*months);
                result+=a;
            }
            case "Personal" -> {
                result=(Personalloan*a)/(100*months);
                result+=a;
            }
            case "Vechile" -> {
                result=(vechileloan*a)/(100*months);
                result+=a;
            }
            default -> {
            }
        }
        if(a>5000) {
      
            JOptionPane.showMessageDialog(this, "Your Balance isn't Enough");
         
        }
        else{
            total.setVisible(true);
        total.setText(Float.toString(result));
             
        } 
        
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void amountcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountcbActionPerformed
      
    }//GEN-LAST:event_amountcbActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bank_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Bank_app().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> amountcb;
    private javax.swing.JButton dash;
    private javax.swing.JPanel dash_Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton loan;
    private javax.swing.JPanel loan_Panel;
    private javax.swing.JButton messages;
    private javax.swing.JPanel messages_Panel;
    private javax.swing.JButton services;
    private javax.swing.JPanel services_Panel;
    private javax.swing.JButton settings;
    private javax.swing.JPanel settings_Panel;
    private javax.swing.JTabbedPane taps;
    private javax.swing.JTextField tf;
    private javax.swing.JTextField total;
    private javax.swing.JButton trans;
    private javax.swing.JPanel trans_Panel;
    private javax.swing.JButton transfer;
    private javax.swing.JPanel transfer_Panel;
    private javax.swing.JComboBox<String> tybecb;
    private javax.swing.JButton wallets;
    private javax.swing.JPanel wallets_Panel;
    // End of variables declaration//GEN-END:variables
}
